// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVLgxR-LBGE79ijx5KIVqYU-T4XNEc1Bc',
    appId: '1:199987603702:web:e8fe56d64acd49f765a4d7',
    messagingSenderId: '199987603702',
    projectId: 'service-finder-app-8c9c3',
    authDomain: 'service-finder-app-8c9c3.firebaseapp.com',
    storageBucket: 'service-finder-app-8c9c3.firebasestorage.app',
    measurementId: 'G-Q4P8DNFRPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSJZAYAc6wNjZeV1-pMalUYOhBVrrC8kA',
    appId: '1:199987603702:android:74e4d219d1fbb27a65a4d7',
    messagingSenderId: '199987603702',
    projectId: 'service-finder-app-8c9c3',
    storageBucket: 'service-finder-app-8c9c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv2A8EJewcQws2F6KPG26mUfEF2n3X8TU',
    appId: '1:199987603702:ios:8c81bfc2b5d6322d65a4d7',
    messagingSenderId: '199987603702',
    projectId: 'service-finder-app-8c9c3',
    storageBucket: 'service-finder-app-8c9c3.firebasestorage.app',
    iosClientId: '199987603702-i85e4h9jkm81t411c4i867mlqqhsscr3.apps.googleusercontent.com',
    iosBundleId: 'lk.uor.serviceProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv2A8EJewcQws2F6KPG26mUfEF2n3X8TU',
    appId: '1:199987603702:ios:ddea5542481f0ae165a4d7',
    messagingSenderId: '199987603702',
    projectId: 'service-finder-app-8c9c3',
    storageBucket: 'service-finder-app-8c9c3.firebasestorage.app',
    iosClientId: '199987603702-s8570cqdphv35i92ubm6vsj1rn0b2uu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.serviceFinderApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVLgxR-LBGE79ijx5KIVqYU-T4XNEc1Bc',
    appId: '1:199987603702:web:5c0bdc147f7b763d65a4d7',
    messagingSenderId: '199987603702',
    projectId: 'service-finder-app-8c9c3',
    authDomain: 'service-finder-app-8c9c3.firebaseapp.com',
    storageBucket: 'service-finder-app-8c9c3.firebasestorage.app',
    measurementId: 'G-8NZEXVDBWX',
  );
}
